name: Lighthouse Check
on: [push]     

jobs:
  lighthouse-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/[email protected]
    - run: mkdir /tmp/artifacts
    - name: Run Lighthouse
      uses: foo-software/[email protected]
      with:
        outputDirectory: /tmp/artifacts
        urls: 'https://archana-p-89.github.io/react/'
    - name: Upload artifacts
      uses: actions/[email protected]
      with:
        name: Lighthouse reports
        path: /tmp/artifacts